"""DEV-ONLY one-off: parse carduka-com-2026-06-29.xlsx into a normalized Python module.

Run from api/ with the venv active:
    python scripts/parse_listings.py > app/seed_data/real_cars.py

This is NOT imported at runtime — the committed app/seed_data/real_cars.py is the
artifact the seeder consumes, so openpyxl and the .xlsx never enter the Docker image.

The six rows flagged below as "sold" are SIMULATED sales derived from real active
listings (synthesized sold_price_kes/sold_at), not real CarDuka transaction data.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

import openpyxl

XLSX = Path(__file__).resolve().parents[2] / "carduka-com-2026-06-29.xlsx"

# row index (1-based, excluding header) -> simulated sale (% of cash price, days ago)
SOLD = {2: (0.95, 24), 4: (0.96, 33), 7: (0.94, 14), 15: (0.97, 19), 17: (0.93, 41), 18: (0.95, 28)}

_BODY = [
    ("hilux", "Pickup"), ("rav", "SUV"), ("harrier", "SUV"), ("prado", "SUV"),
    ("cayenne", "SUV"), ("discovery", "SUV"), ("juke", "SUV"), ("vezel", "SUV"),
    ("3008", "SUV"), ("rx200", "SUV"), ("a-class", "Hatchback"), ("demio", "Hatchback"),
    ("mira", "Hatchback"), ("fit", "Hatchback"), ("ad", "Station Wagon"),
    ("axio", "Sedan"), ("320i", "Sedan"), ("3 series", "Sedan"),
]


def _col(hdr, row, name):
    try:
        return row[hdr.index(name)]
    except (ValueError, IndexError):
        return None


def _int(text) -> int | None:
    if text is None:
        return None
    m = re.search(r"(\d[\d,]*)", str(text).replace(" ", ""))
    return int(m.group(1).replace(",", "")) if m else None


def _body_type(model: str, cfg: str) -> str:
    blob = f"{model} {cfg}".lower()
    for key, bt in _BODY:
        if key in blob:
            return bt
    return "Sedan"


def _image(hdr, row) -> str:
    for name in ["image"] + [f"image{i}" for i in range(2, 11)] + ["image_1"]:
        url = _col(hdr, row, name)
        if url and "prodapi.ncbagroup.com" in str(url) and "logo" not in str(url):
            return str(url)
    return ""


def main() -> None:
    wb = openpyxl.load_workbook(XLSX, read_only=True, data_only=True)
    ws = wb["Sheet1"]
    rows = list(ws.iter_rows(values_only=True))
    hdr = list(rows[0])

    active: list[dict] = []
    sold: list[dict] = []
    for i, row in enumerate(rows[1:], 1):
        title = str(_col(hdr, row, "data") or "")
        make = (str(_col(hdr, row, "name") or "")).strip()
        cfg = (str(_col(hdr, row, "vehicleConfiguration") or "")).strip()
        ym = re.match(r"(\d{4})", title)
        year = int(ym.group(1)) if ym else 2015
        model = cfg.split()[0] if cfg else "Unknown"
        price = _int(_col(hdr, row, "data3")) or _int(_col(hdr, row, "priceCurrency"))
        mileage = _int(_col(hdr, row, "data4")) or _int(_col(hdr, row, "data_10")) or 0
        trans = (str(_col(hdr, row, "vehicletransmission") or "automatic")).strip().title()
        if trans.lower() == "cvt":
            trans = "Automatic"
        fuel = (str(_col(hdr, row, "fueltype") or "petrol")).strip().title()
        loc = (str(_col(hdr, row, "data7") or "Nairobi")).split(",")[0].strip()
        desc = (str(_col(hdr, row, "car_description") or _col(hdr, row, "description") or "")).strip()
        desc = re.sub(r"\s+", " ", desc)[:280]
        if not make or not price:
            continue
        rec = {
            "id": f"car_real_{i:02d}",
            "make": make,
            "model": model,
            "year": year,
            "price_kes": price,
            "mileage_km": mileage,
            "transmission": trans,
            "fuel": fuel,
            "location": loc or "Nairobi",
            "condition": "Good",
            "body_type": _body_type(model, cfg),
            "image_url": _image(hdr, row),
            "description": desc,
        }
        if i in SOLD:
            pct, days = SOLD[i]
            rec["sold_price_kes"] = int(price * pct)
            rec["sold_days_ago"] = days
            sold.append(rec)
        else:
            active.append(rec)

    out = sys.stdout
    out.write('"""Real CarDuka listings parsed from carduka-com-2026-06-29.xlsx '
              '(generated by scripts/parse_listings.py).\n\n'
              'REAL_ACTIVE are genuine scraped listings (real prices, descriptions, NCBA CDN\n'
              'image URLs). REAL_SOLD are SIMULATED sales derived from real listings\n'
              '(synthesized sold_price_kes/sold_at) used only as price-verdict comparables —\n'
              'NOT real CarDuka transaction data.\n"""\n')
    out.write("from __future__ import annotations\n\n")
    out.write("REAL_ACTIVE = [\n")
    for r in active:
        out.write(f"    {r!r},\n")
    out.write("]\n\n")
    out.write("REAL_SOLD = [\n")
    for r in sold:
        out.write(f"    {r!r},\n")
    out.write("]\n")


if __name__ == "__main__":
    main()
